services:
  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devbook
    ports:
      - "3306:3306"
    volumes:
      - ./src/migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql